# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

# extra debug messages
DEFS+=-DDBT_EXTRA_DEBUG
 
include ../../Makefile.defs
auto_gen=
NAME=dbtext.so
LIBS=

include ../../Makefile.modules
