# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# database example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbtex.so
LIBS=

include ../../Makefile.modules
