# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# acc_syslog - Accounting into syslog
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=acc_db.so
LIBS=

include ../../Makefile.modules
