REGISTER sip:10.109.247.207 SIP/2.0
Call-ID: 0HH1JvDcNT8aFk5nhutsuH4THFgy@10.109.247.207
CSeq: 1 REGISTER
From: "linfeng" <sip:alice@10.109.247.207>;tag=1000
To: "linfeng" <sip:alice@10.109.247.207>
Via: SIP/2.0/UDP 10.109.247.207:5067;branch=z9hG4bK-MIfacKqHPJaVez2Sm6LbUDhhHPI
Max-Forwards: 20
Expires: 10800
Authorization: Digest username="alice@10.109.247.207",realm="10.109.247.207",nonce="",response="",uri="sip:10.109.247.207"
Supported: path
Contact: 65535sip:10.109.247.207:5067>
P-Preferred-Identity: "linfeng" <sip:alice@10.109.247.207>
P-Access-Network-Info: 3GPP-UTRAN-TDD; utran-cell-id-3gpp=00000000
Privacy: none
User-Agent: Fraunhofer FOKUS/NGNI Java IMS UserEndpoint FoJIE 0.1 (jdk1.3)
Allow: INVITE,ACK,CANCEL,BYE,MESSAGE,NOTIFY
Content-Length: 0

