# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
# rr module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=rr.so
LIBS=

include ../../Makefile.modules
