# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# db_ops module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=db_ops.so
LIBS=


include ../../Makefile.modules


