# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=pike.so
LIBS= 

include ../../Makefile.modules
