# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
# database example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbtex.so
LIBS=

include ../../Makefile.modules
