# $Id: Makefile 166 2007-03-02 19:28:23Z vingarzan $
#
# opt_rpl module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=options.so
LIBS=

include ../../Makefile.modules
