# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# sanity check module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=sanity.so
LIBS=

include ../../Makefile.modules
