# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=ctl.so
LIBS=
# fifo support
DEFS+=-DUSE_FIFO

include ../../Makefile.modules

