# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
#  serunix Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=serunix
LIBS:=$(filter-out -lfl, $(LIBS) )

include ../../Makefile.sources
include ../../Makefile.rules


modules:
