# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=xmlrpc.so
DEFS += -I/usr/include/libxml2 -I/usr/local/include/libxml2 -I/usr/local/include
LIBS +=-lxml2

include ../../Makefile.modules

