# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
#  gen_ha1 Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=gen_ha1
LIBS=../../md5.o


include ../../Makefile.sources
include ../../Makefile.rules

modules:
