##	config.rb
$SIPDB = "opensipstackdb"
$DBG = "off"
$YAML_FILE = 'sips_info.yaml'
$SIP_REGISTER = {
	# "Method" => "",
	"Request-URI" => ["request[-_]?uri", "Request.URI"],
	"Via" => ["via", "Via"],
	"From" => ["from", "From"],
	"Contact" => ["contact", "Contact"],
	"To" => ["to", "To"],
	"Call-Id" => ["call[-_]?id", "Call.Id"],
	"Expires" => ["expires", "Expires"],
	"Max-Forwards" => ["max[-_]?forwards", "Max.Forwards"],
	"Cseq" => ["cseq", "Cseq"],
	"Content-Type" => ["content[-_]?type", "Content.Type"],
	"Content-Length" => ["content[-_]?length", "Content.Length"],
	"Request-CRLF" => ["request[-_]?crlf", "Request.CRLF"]
}
$SIPHD = {
	:from => "From",
	:to => "To",
	#:call_id => "Call-ID",
	:cseq => "Cseq",
	:via => "Via",
	:allow => "Allow"	#header?Allow}
	
	# :authenticate => "authenticate",
	# :call_info => "call_info",
	# :content => "content",
	# :cseq => "cseq",
	# :disposition => "disposition",
	# :diversion => "diversion",
	# :event => "event",
	# :expires => "expires",
	# :fline => "fline",
	# :from => "from",
	# :hname2 => "hname2",
	# :methods => "methods",
	# :min_expires => "min_expires",
	# :multipart => "multipart",
	# :nameaddr => "nameaddr",
	# :pai => "pai",
	# :param => "param",
	# :ppi => "ppi",
	# :privacy => "privacy",
	# :refer_to => "refer_to",
	# :replaces => "replaces",
	# :parser_f => "parser_f",
	# :rpid => "rpid",
	# :rr => "rr",
	# :sipifmatch => "sipifmatch",
	# :sst => "sst",
	# :supported => "supported",
	# :to => "to",
	# :uri => "uri",
	# :via => "via"
}
$SIP_HD = {
	"Request-Line" => "",	# => Method SP Request-URI SP SIP-Version CRLF; Start-Line
	"Message-Header" => "", # => Header-Name HCOLON Header-Value * (COMMA Header-Value); 

}
$BASE_SIP_HD = {
	"From" => :from,
	"To" => :to,
	"Call-ID" => :call_id,
	"Contact" => :contact,
	"CSeq" => :cseq,
	"Max-Forward" => "",
	"Via" => "",
	"Content-Type" => "",
	"Content-Length" => ""
}
$OPENSIPS_SIP_HD = {
    :via => {"parse_via" => ""},
    :callid => {"parse_replaces" => ""},
    :to => {"parse_to" => ""},
    :cseq => {"parse_cseq" => ""},
    :from => {"parse_from" => ""},
    :contact => {"parse_param" => "parse_contact_class", "parse_contact" => "", "contact" => ""},
    #:maxforwards => {"" => ""},
    :route => {"parse_rr" => ""},
    :record_route => {"parse_rr" => ""},
    :path => {"parse_rr" => "get_path_dst_uri"},
    :content_type => {"parse_content" => "", "parse_multipart" => ""},
    :content_length => {"parse_content" => ""},
    :authorization => {"" => ""},
    :expires => {"" => ""},
    :proxy_auth => {"" => ""},
    :supported => {"" => ""},
    :proxy_require => {"" => ""},
    :unsupported => {"" => ""},
    :allow => {"" => ""},
    :event => {"" => ""},
    :accept => {"" => ""},
    :accept_language => {"" => ""},
    :organization => {"" => ""},
    :priority => {"" => ""},
    :subject => {"" => ""},
    :user_agent => {"" => ""},
    :content_disposition => {"" => ""},
    :accept_disposition => {"" => ""},
    :diversion => {"" => ""},
    :rpid => {"" => ""},
    :refer_to => {"" => ""},
    :session_expires => {"" => ""},
    :min_se => {"" => ""},
    :ppi => {"" => ""},
    :pai => {"" => ""},
    :privacy => {"" => ""},
    :call_info => {"" => ""},
    :www_authenticate => {"" => ""},
    :proxy_authenticate => {"" => ""},
    :min_expires => {"" => ""}
}

$OPENSIPS_FILES_HD = {
	:allow => "allow",
	:authenticate => "authenticate",
	:call_info => "call_info",
	:content => "content",
	:cseq => "cseq",
	:disposition => "disposition",
	:diversion => "diversion",
	:event => "event",
	:expires => "expires",
	:fline => "fline",
	:from => "from",
	:hname2 => "hname2",
	:methods => "methods",
	:min_expires => "min_expires",
	:multipart => "multipart",
	:nameaddr => "nameaddr",
	:pai => "pai",
	:param => "param",
	:ppi => "ppi",
	:privacy => "privacy",
	:refer_to => "refer_to",
	:replaces => "replaces",
	:parser_f => "parser_f",
	:rpid => "rpid",
	:rr => "rr",
	:sipifmatch => "sipifmatch",
	:sst => "sst",
	:supported => "supported",
	:to => "to",
	:uri => "uri",
	:via => "via"
}
