#
# $Id: Makefile.sources 166 2007-03-02 19:28:23Z vingarzan $
#
# common Makefile variables 
# (source files, objs, etc)


#
# expects: auto_gen defined
#
# defines: sources, objs, depends
#

sources=$(filter-out $(auto_gen), $(wildcard *.c) $(wildcard mem/*.c) \
		$(wildcard parser/*.c) $(wildcard parser/digest/*.c) \
		$(wildcard parser/contact/*.c) $(wildcard db/*.c) ) $(auto_gen)
ifeq ($(CORE_TLS), 1)
	sources+= $(wildcard tls/*.c)
endif
objs=$(sources:.c=.o)
extra_objs=
depends=$(sources:.c=.d)
modules=
static_modules=
static_modules_path=
