# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
# URI checks using Radius
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=uri_radius.so

include ../../Makefile.modules
