# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
# Digest Authentication - Radius support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=auth_radius.so


include ../../Makefile.modules
