# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
# Diversion Header Field Support2
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=diversion.so
LIBS=

include ../../Makefile.modules
