# $Id: Makefile 165 2007-03-02 15:15:46Z vingarzan $
#
#  serunix Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=serunix
LIBS:=$(filter-out -lfl, $(LIBS) )

include ../../Makefile.sources
include ../../Makefile.rules


modules:
