# $Id: Makefile 2 2006-11-14 22:37:20Z vingarzan $
#
#  gen_ha1 Makefile
# 

include ../../Makefile.defs

auto_gen=
NAME=gen_ha1
LIBS=../../md5.o


include ../../Makefile.sources
include ../../Makefile.rules

modules:
